"""create recipes table

Revision ID: eadc874612b9
Revises: 8947302a4dfc
Create Date: 2024-10-28 08:18:40.525599

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eadc874612b9'
down_revision: Union[str, None] = '8947302a4dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'recipes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome_refeicao', sa.String(), nullable=False),
        sa.Column('nome_alimento', sa.String(), nullable=False),
        sa.Column('nome_categoria', sa.String(), nullable=False),
        sa.Column('quantidade', sa.String(), nullable=False),
        sa.Column('kcal', sa.Integer(), nullable=False),
        sa.Column('dia_semana', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
